### ISSUE TITLE
Encountered EXC_BAD_ACCESS in dispatch(ReSwiftInit()) on Xcode 11.2

### ISSUE THREAD

**Issue by adamhongmy** [ReSwift/ReSwift#430] opened 2019-11-02 04:23 UTC
Hi, 
After updating Xcode from 11.1 to 11.2, and this happened (screenshot below) when I call my Store class.
<img width="804" alt="Screenshot 2019-11-02 at 10 13 12 AM" src="https://user-images.githubusercontent.com/11060748/68065868-5111ea00-fd6a-11e9-97f2-2937f65bb93a.png">

I don't know much memory debugging but I tried running with Address Sanitizer enabled, it didn't crash at all. 

To confirm it is Xcode 11.2 problem, I download Xcode 11.1 and run my project on it and it didn't crash too.

I was wondering if anyone have this issue too?

**Comment by noppefoxwolf** [comment] 2019-11-02 06:45
+1

**Comment by ydnar** [comment] 2019-11-02 18:33
The issue is related to stripped generic symbols. Try disabling dead code stripping on your app’s project: DEAD_CODE_STRIPPING = NO 

https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564

**Comment by DivineDominion** [comment] 2019-11-08 19:21
I'm closing this since so many thumbs-ups were pouring in to a known bug

**Closed by DivineDominion** 2019-11-08 19:21 UTC
