### ISSUE TITLE
Compilation fails if swiftlint is installed

### ISSUE THREAD

**Issue by buscarini** [ReSwift/ReSwift#233] opened 2017-04-06 11:20 UTC
I'm using Carthage with the following configuration:

    github "ReSwift/ReSwift" == 3.0.0

and I was seeing this error all the time:

    Build Failed
    Task failed with exit code 65:

It seems that swiftlint fails at some of the shell scripts and so the Carthage compilation fails. This only happens with some latest versions of swiftlint (0.16.1, 0.17). A workmate has an older version (0.11) and it works for him.

I tried the master branch and it works with that one, but I'd rather use a stable version. I think the solution here would be to disable swiftlint for carthage compilations, though I'm not sure how that can be done.

**Comment by Ben-G** [comment] 2017-04-06 15:04
@buscarini Thanks for bringing this up. It appears that Carthage actually has support for this: https://github.com/Carthage/Carthage/pull/1154. We should just incorporate a check for the env variable into the build script phase that calls SwiftLint, and skip it if we are running under carthage.

**Comment by mjarvis** [comment] 2017-04-06 15:14
Does this occur with the changes in https://github.com/ReSwift/ReSwift/pull/218 ?

**Comment by Ben-G** [comment] 2017-04-06 15:17
@mjarvis Good point I forgot about; if that PR gets merged our problems are resolved as well.

**Comment by mokagio** [comment] 2017-04-11 21:03
Sorry, closed issue rather than closing tab 😳 .

**Comment by mjarvis** [comment] 2017-04-11 21:04
I think closing the issue is appropriate here, as #218 has been merged and this should therefore be fixed in the upcoming 4.0.0 release

**Closed by mjarvis** 2017-04-11 21:04 UTC
