### ISSUE TITLE
Store entities do not deinitialize (dealloc) when no longer owned (Memory Leak)

### ISSUE THREAD

**Issue by JesseARWhite** [ReSwift/ReSwift#66] opened 2016-01-29 21:49 UTC
How to reproduce:
1.  Add a deinit callback to the Store class to know that a store has been deallocated
2.  New up a store in memory that is not owned (meaning it should be deallocated on the next run loop)
3.  deinit will not get called at runtime, meaning the store has a memory leak
4.  Comment out the following lines:
        self.dispatchFunction = middleware.reverse().reduce(_defaultDispatch) {
            [weak self] dispatchFunction, middleware in
                let getState = { self?.state }
                return middleware(self?.dispatch, getState)(dispatchFunction)
        }
5.  Re-test, store now deallocates properly

It appears that the dispatch function is ultimately holding a reference to the store object itself, making it impossible for the store to go away and free up the memory it was using if it was using.  Consequently it also holds onto any reducers and subscribers.  Allowing the store to deallocate will allow all referenced objects to deallocate as well.

**Comment by Ben-G** [comment] 2016-01-29 22:30
Nice catch! I planned on looking into this. I assume the '_defaultDispatch' reference is the cause of the issue. 

Will look into this next week (after vacation), but a fix as PR is appreciated as well :)

**Comment by Ben-G** [comment] 2016-02-06 23:41
Closed by #72.

**Closed by Ben-G** 2016-02-06 23:41 UTC
Labels: Bug
